name = banghouse
description = Custom Bang! House layout

regions[navigation] = Navigation
regions[banner] = Banner
regions[search] = Search
regions[preface] = Preface
regions[content] = Content
regions[postscript] = Postscript
regions[footer] = Footer
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar

stylesheets[all][] = css/banghouse.layout.css
stylesheets[all][] = css/banghouse.styles.css
scripts[] = js/banghouse.layout.js

preview = preview.png
